INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 513, 'osíxeno ceibe' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 513, 'ceo aberto' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 514, 'agresión cardíaca' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 514, 'infarto' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 515, 'inspección externa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 516, 'alerta amarela' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 516, 'alerta de nivel baixo' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 517, 'banda grosa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 517, 'internet de alta velocidade' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 518, 'faixa acústica' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 518, 'cancións dun filme' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 519, 'bandeira de cor negra' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 519, 'praia contaminada' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 519, 'sinal de protesto' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 520, 'brazos separados' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 520, 'cordialmente' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 521, 'burato de cor negra' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 521, 'obxecto celeste' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 521, 'débeda económica' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 522, 'camisa de cor branca' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 523, 'casco protector vello' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 523, 'parte histórica da cidade' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 524, 'institución educativa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 525, 'núcleo nervioso' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 525, 'lugar máis frecuentado' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 526, 'cidade ruinosa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 526, 'parte histórica da cidade' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 527, 'categoria elevada' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 527, 'burguesía' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 528, 'xornada habilidosa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 528, 'día laborable' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 529, 'enerxía non contaminante' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 530, 'fendedura dactilar' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 530, 'diferenza de acceso ás novas tecnoloxías' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 531, 'festexo fendido' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 531, 'festa grande' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 532, 'célula sanguínea pigmentada' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 533, 'choque con forza' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 533, 'impedimento' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 534, 'horas reducidas' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 534, 'mal momento' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 534, 'período de pouca actividade' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 535, 'incendio no monte' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 536, 'madeira húmida' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 536, 'xente nova' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 537, 'conexión falecida' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 537, 'link sen destino' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 538, 'idioma galego' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 539, 'fogo vagaroso' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 539, 'pouca temperatura' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 539, 'a pouca velocidade' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 540, 'iluminación verde' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 540, 'aprobación' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 541, 'iluminación encarnada' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 541, 'prohibición' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 541, 'sospeita' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 542, 'acumulación económica' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 542, 'conxunto de retribucións' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 543, 'material negro' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 543, 'materia cósmica descoñecida' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 544, 'lembranza vivente' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 544, 'recordos populares' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 544, 'personalidade relevante que aínda vive' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 545, 'monte de pouca altitude' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 545, 'monte con arbustos pequenos' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 546, 'corazón' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 546, 'institución principal' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 546, 'instrumento máis importante' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 547, 'paseo polo mar' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 547, 'camiño construído á beira do mar' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 548, 'pisada natural' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 548, 'indicador de sustentabilidade das actividades humanas' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 549, 'poboamento animado' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 549, 'persoas que poden traballar' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 550, 'acceso amplo' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 550, 'alta reputación' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 551, 'lugar robusto' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 551, 'virtude' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 552, 'lugar aseado' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 552, 'depósito de residuos' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 553, 'mancha de cor negra' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 553, 'tramo de concentración de accidentes' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 553, 'zona contaminada' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 554, 'rédito simple' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 554, 'subsidio esencial' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 555, 'brinco cualitativo' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 555, 'avance importante' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 556, 'momento sombrío' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 556, 'período decadente' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 557, 'momento fragmentario' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 557, 'xornada de traballo reducida' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 557, 'compatibilización entre varias tarefas' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 558, 'sexta feira escura' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 558, 'xornada negativa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 558, 'descontos na compra online' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 559, 'parte da vida dedicada ao traballo' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 559, 'informe do traballos realizados' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 560, 'vida dunha persoa' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 560, 'realidade' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 561, 'vivenda vacía' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 561, 'vivenda sen protección oficial' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 562, 'xente descoñecida' );
INSERT INTO meanings ( idiom_id, meaning ) VALUES ( 562, 'persoas de pouca idade' );
